# Generated by Django 3.2.12 on 2024-10-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='TiposTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=100, verbose_name='Dia da Semana')),
                ('treino', models.CharField(max_length=100, verbose_name='Treino')),
            ],
            options={
                'verbose_name': 'Tipo de Treinamento',
                'verbose_name_plural': 'Tipos de Treinamento',
            },
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('alunos_responsavel', models.ManyToManyField(blank=True, related_name='alunos_responsavel', to='gerencia.Aluno', verbose_name='Alunos Responsável')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipos_treinamento',
            field=models.ManyToManyField(blank=True, related_name='tipos_treinamento', to='gerencia.TiposTreinamento', verbose_name='Tipos de Treinamento'),
        ),
    ]
