# Generated by Django 3.2.12 on 2024-10-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0002_alter_tipostreinamento_dia_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipostreinamento',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='tipostreinamento',
            name='treino',
        ),
        migrations.AddField(
            model_name='tipostreinamento',
            name='nome_exercicio',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do Exercício'),
        ),
        migrations.AddField(
            model_name='tipostreinamento',
            name='nome_treino',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do Treinamento'),
        ),
        migrations.AddField(
            model_name='tipostreinamento',
            name='repeticoes',
            field=models.IntegerField(default=0, verbose_name='Repetições'),
        ),
        migrations.AddField(
            model_name='tipostreinamento',
            name='series',
            field=models.IntegerField(default=0, verbose_name='Séries'),
        ),
        migrations.AddField(
            model_name='tipostreinamento',
            name='tempo_descanso',
            field=models.IntegerField(default=0, verbose_name='Tempo de Descanso'),
        ),
    ]
