# Generated by Django 3.2.12 on 2024-10-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0003_auto_20241020_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dias_treino',
            field=models.IntegerField(default=0, verbose_name='Dias de Treino'),
        ),
    ]
