# Generated by Django 3.2.12 on 2024-10-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0004_aluno_dias_treino'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='treinos_realizados_semana',
            field=models.ManyToManyField(blank=True, related_name='treinos_realizados', to='gerencia.TiposTreinamento', verbose_name='Treinos Realizados na Semana'),
        ),
    ]
