# Generated by Django 3.2.12 on 2024-10-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0005_aluno_treinos_realizados_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dias_treino_inicial',
            field=models.IntegerField(default=0, verbose_name='Dias de Treino Inicial'),
        ),
    ]
