# Generated by Django 3.2.12 on 2024-10-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0006_aluno_dias_treino_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipostreinamento',
            name='dia_semana',
            field=models.CharField(choices=[('Segunda', 'Segunda-feira'), ('Terca', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], default='', max_length=10, verbose_name='Dia da Semana'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dias_treino',
            field=models.IntegerField(default=0, verbose_name='Dias de Treino restantes'),
        ),
    ]
