# Generated by Django 3.2.12 on 2024-10-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Profesor', 'Professor'), ('Gerente', 'Gerente')], default='', max_length=100, verbose_name='Tipo de Usuário'),
        ),
    ]
